services:
  mongo:
    image: l33tlamer/mongodb-without-avx:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    image: geolocation-app:latest
    container_name: geolocation-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development

volumes:
  mongo-data:
  node_modules: